apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-mongo
  labels:
    something: mongodb
spec:
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-node
          image: mongo
          ports:
            - containerPort: 27017
