apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-node
  labels:
    something: nodejs-app
spec:
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app

  template:
    metadata:
      name: node-app-mongo-pod
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: node-app-nodea
          image: hieppm3/node-app
          env:
           - name: MONGODB_URI
             value: "mongodb://mongodb-svc:27017/demo"
          ports:
            - containerPort: 3000
